language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 7
  - nvm use 7
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  - bin/checkDevOnly $TRAVIS_SCALA_VERSION

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache